### create a user
### fails if username already exists
POST http://localhost:3003/api/users
Content-Type: application/json

{
	"username": "anotheruser",
	"name": "Garby L",
  "password": "pazzword"
	# "username": "mlukkkai2",
	# "name": "Matti L",
  # "password": "pazzword"
}
### fail: password < 3 length
POST http://localhost:3003/api/users
Content-Type: application/json

{
	"username": "shuhdintwork",
	"name": "Matti L",
  "password": "ab"
}

### fail: username < 3 length
POST http://localhost:3003/api/users
Content-Type: application/json

{
	"username": "ab",
	"name": "Matti L",
  "password": "abzzz"
}

### fail: password missing
POST http://localhost:3003/api/users
Content-Type: application/json

{
	"username": "ab",
	"name": "Matti L"
}

### fail: username missing
POST http://localhost:3003/api/users
Content-Type: application/json

{
	"name": "Matti L",
  "password": "abzzz"
}

### Get all users
GET http://localhost:3003/api/users
