### Add a new person to the phonebook
POST http://localhost:3001/api/persons
Content-Type: application/json

{
    "name": "Jabron Lamarkie",
    "number": "522332-23"
}

### Add a person fails due to missing number
POST http://localhost:3001/api/persons
Content-Type: application/json

{
    "name": "Jabron Lamarkie"
}

### Add a person fails due to missing name
POST http://localhost:3001/api/persons
Content-Type: application/json

{
    "number": "522332-23"
}

### Add a person fails due to duplicate
POST http://localhost:3001/api/persons
Content-Type: application/json

{
    "name": "Tony Tiger",
    "number": "522332-23"
}

### Add a new person fails due to name < 3 length
POST http://localhost:3001/api/persons
Content-Type: application/json

{
    "name": "Ja",
    "number": "12345678"
}


### Add a new person fails due to number < 8 length
POST http://localhost:3001/api/persons
Content-Type: application/json

{
    "name": "Jab",
    "number": "1234567"
}

